version: '3.1'

services:
  proxy:
    image: nginx
    ports:
      - 8866:443
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/html"
      - "./nginx/ssl:/etc/nginx/ssl"